use_frameworks!

platform :ios, '9.0'

target 'RTFlexLayout_Example' do
  pod 'RTFlexLayout', :path => '../'
  pod 'YogaKit', :path => '../../Yoga'
  pod 'Yoga', :path => '../../Yoga'

  target 'RTFlexLayout_Tests' do
    inherit! :search_paths

    
  end
end
